// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $factory_index from "./routes/factory/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $merge_index from "./routes/merge/index.tsx";
import * as $factory_Factory from "./islands/factory/Factory.tsx";
import * as $factory_NewEmployee from "./islands/factory/NewEmployee.tsx";
import * as $merge_MergeSort from "./islands/merge/MergeSort.tsx";
import * as $merge_TextInput from "./islands/merge/TextInput.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/factory/index.tsx": $factory_index,
    "./routes/index.tsx": $index,
    "./routes/merge/index.tsx": $merge_index,
  },
  islands: {
    "./islands/factory/Factory.tsx": $factory_Factory,
    "./islands/factory/NewEmployee.tsx": $factory_NewEmployee,
    "./islands/merge/MergeSort.tsx": $merge_MergeSort,
    "./islands/merge/TextInput.tsx": $merge_TextInput,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
